# Linear Regression

In [53]:
import numpy as np
import pandas as pd

In [54]:
train_file=r'C:/Users/DELL/Desktop/Wasim/Learning/Data Scientist/Edvancer Old Study Material/Data/loan_data_train.csv'
test_file=r'C:/Users/DELL/Desktop/Wasim/Learning/Data Scientist/Edvancer Old Study Material/Data/loan_data_test.csv'

ld_train=pd.read_csv(train_file)
ld_test=pd.read_csv(test_file)

In [55]:
ld_test.head()

,ID,Amount.Requested,Amount.Funded.By.Investors,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
0,20093,5000,5000,60 months,moving,12.59%,NY,RENT,4416.67,690-694,13,7686,0,< 1 year
1,62445,18000,18000,60 months,debt_consolidation,4.93%,CA,RENT,5258.50,710-714,6,11596,0,10+ years
2,65248,7200,7200,60 months,debt_consolidation,25.16%,LA,MORTGAGE,3750.00,750-754,13,7283,0,6 years
3,81822,7200,7200,36 months,debt_consolidation,17.27%,NY,MORTGAGE,3416.67,790-794,14,4838,0,10+ years
4,57923,22000,22000,60 months,debt_consolidation,18.28%,MI,MORTGAGE,6083.33,720-724,9,20181,0,8 years

In [56]:
ld_train.head()

,ID,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
0,79542.0,25000,25000,18.49%,60 months,debt_consolidation,27.56%,VA,MORTGAGE,8606.56,720-724,11,15210,3.0,5 years
1,75473.0,19750,19750,17.27%,60 months,debt_consolidation,13.39%,NY,MORTGAGE,6737.50,710-714,14,19070,3.0,4 years
2,67265.0,2100,2100,14.33%,36 months,major_purchase,3.50%,LA,OWN,1000.00,690-694,13,893,1.0,< 1 year
3,80167.0,28000,28000,16.29%,36 months,credit_card,19.62%,NV,MORTGAGE,7083.33,710-714,12,38194,1.0,10+ years
4,17240.0,24250,17431.82,12.23%,60 months,credit_card,23.79%,OH,MORTGAGE,5833.33,730-734,6,31061,2.0,10+ years

In [57]:
# lets combine the data for data prep

ld_test['Interest.Rate']=np.nan
ld_train['data']='train'
ld_test['data']='test'
ld_test=ld_test[ld_train.columns]
ld_all=pd.concat([ld_train,ld_test],axis=0)

In [58]:
ld_all.head()

,ID,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length,data
0,79542.0,25000,25000,18.49%,60 months,debt_consolidation,27.56%,VA,MORTGAGE,8606.56,720-724,11,15210,3.0,5 years,train
1,75473.0,19750,19750,17.27%,60 months,debt_consolidation,13.39%,NY,MORTGAGE,6737.50,710-714,14,19070,3.0,4 years,train
2,67265.0,2100,2100,14.33%,36 months,major_purchase,3.50%,LA,OWN,1000.00,690-694,13,893,1.0,< 1 year,train
3,80167.0,28000,28000,16.29%,36 months,credit_card,19.62%,NV,MORTGAGE,7083.33,710-714,12,38194,1.0,10+ years,train
4,17240.0,24250,17431.82,12.23%,60 months,credit_card,23.79%,OH,MORTGAGE,5833.33,730-734,6,31061,2.0,10+ years,train

In [59]:
ld_all.dtypes

ID                                float64
Amount.Requested                   object
Amount.Funded.By.Investors         object
Interest.Rate                      object
Loan.Length                        object
Loan.Purpose                       object
Debt.To.Income.Ratio               object
State                              object
Home.Ownership                     object
Monthly.Income                    float64
FICO.Range                         object
Open.CREDIT.Lines                  object
Revolving.CREDIT.Balance           object
Inquiries.in.the.Last.6.Months    float64
Employment.Length                  object
data                               object
dtype: object

In [60]:
ld_all.drop(['ID','Amount.Funded.By.Investors'],axis=1,inplace=True)

In [61]:
for col in ['Interest.Rate','Debt.To.Income.Ratio']:
    ld_all[col]=ld_all[col].str.replace("%","")

In [62]:
for col in ['Amount.Requested','Interest.Rate','Debt.To.Income.Ratio',
           'Open.CREDIT.Lines','Revolving.CREDIT.Balance']:
    ld_all[col]=pd.to_numeric(ld_all[col],errors='coerce')

In [63]:
k=ld_all['FICO.Range'].str.split("-",expand=True).astype(float)

ld_all['fico']=0.5*(k[0]+k[1])

del ld_all['FICO.Range']

In [64]:
ld_all['Employment.Length'].value_counts()

10+ years    653
< 1 year     249
2 years      243
3 years      235
5 years      202
4 years      191
1 year       177
6 years      163
7 years      127
8 years      108
9 years       72
.              2
Name: Employment.Length, dtype: int64

In [65]:
ld_all['Employment.Length']=ld_all['Employment.Length'].str.replace('years',"")

ld_all['Employment.Length']=ld_all['Employment.Length'].str.replace('year',"")

ld_all['Employment.Length']=np.where(ld_all['Employment.Length'].str[:2]=="10",10,ld_all['Employment.Length'])

ld_all['Employment.Length']=np.where(ld_all['Employment.Length'].str[0]=="<",0,ld_all['Employment.Length'])

ld_all['Employment.Length']=pd.to_numeric(ld_all['Employment.Length'],errors='coerce')

In [66]:
# Notice that to apply string function on pandas data frame columns you need to str attribute
cat_cols=ld_all.select_dtypes(['object']).columns

In [67]:
cat_cols

Index(['Loan.Length', 'Loan.Purpose', 'State', 'Home.Ownership', 'data'], dtype='object')

In [68]:
cat_cols=cat_cols[:-1]

In [69]:
cat_cols

Index(['Loan.Length', 'Loan.Purpose', 'State', 'Home.Ownership'], dtype='object')

In [70]:
# you can use following method if you want to ignore categories with too low frequencies ,
# in next section for logistic regression we will be using pandas' get dummies function.
# you can work with either of these.
# ignoring categories with low frequencies however will result in fewer columns without
# affecting model performance too much.

for col in cat_cols:
    freqs=ld_all[col].value_counts()
    k=freqs.index[freqs>20][:-1]
    for cat in k:
        name=col+'_'+cat
        ld_all[name]=(ld_all[col]==cat).astype(int)
    del ld_all[col]
    print(col)

Loan.Length
Loan.Purpose
State
Home.Ownership

In [71]:
ld_all.shape

(2500, 51)

In [72]:
ld_all.isnull().sum()

Amount.Requested                     5
Interest.Rate                      300
Debt.To.Income.Ratio                 1
Monthly.Income                       3
Open.CREDIT.Lines                    9
Revolving.CREDIT.Balance             5
Inquiries.in.the.Last.6.Months       3
Employment.Length                   80
data                                 0
fico                                 0
Loan.Length_36 months                0
Loan.Purpose_debt_consolidation      0
Loan.Purpose_credit_card             0
Loan.Purpose_other                   0
Loan.Purpose_home_improvement        0
Loan.Purpose_major_purchase          0
Loan.Purpose_small_business          0
Loan.Purpose_car                     0
Loan.Purpose_wedding                 0
Loan.Purpose_medical                 0
Loan.Purpose_moving                  0
State_CA                             0
State_NY                             0
State_TX                             0
State_FL                             0
State_IL                             0
State_GA                             0
State_PA                             0
State_NJ                             0
State_VA                             0
State_MA                             0
State_OH                             0
State_MD                             0
State_NC                             0
State_CO                             0
State_WA                             0
State_CT                             0
State_AZ                             0
State_MI                             0
State_AL                             0
State_MN                             0
State_MO                             0
State_NV                             0
State_OR                             0
State_SC                             0
State_WI                             0
State_KY                             0
State_LA                             0
State_OK                             0
Home.Ownership_MORTGAGE              0
Home.Ownership_RENT                  0
dtype: int64

In [73]:
for col in ld_all.columns:
    if (col not in ['Interest.Rate','data'])& (ld_all[col].isnull().sum()>0):
        ld_all.loc[ld_all[col].isnull(),col]=ld_all.loc[ld_all['data']=='train',col].mean()

In [74]:
ld_all.isnull().sum()

Amount.Requested                     0
Interest.Rate                      300
Debt.To.Income.Ratio                 0
Monthly.Income                       0
Open.CREDIT.Lines                    0
Revolving.CREDIT.Balance             0
Inquiries.in.the.Last.6.Months       0
Employment.Length                    0
data                                 0
fico                                 0
Loan.Length_36 months                0
Loan.Purpose_debt_consolidation      0
Loan.Purpose_credit_card             0
Loan.Purpose_other                   0
Loan.Purpose_home_improvement        0
Loan.Purpose_major_purchase          0
Loan.Purpose_small_business          0
Loan.Purpose_car                     0
Loan.Purpose_wedding                 0
Loan.Purpose_medical                 0
Loan.Purpose_moving                  0
State_CA                             0
State_NY                             0
State_TX                             0
State_FL                             0
State_IL                             0
State_GA                             0
State_PA                             0
State_NJ                             0
State_VA                             0
State_MA                             0
State_OH                             0
State_MD                             0
State_NC                             0
State_CO                             0
State_WA                             0
State_CT                             0
State_AZ                             0
State_MI                             0
State_AL                             0
State_MN                             0
State_MO                             0
State_NV                             0
State_OR                             0
State_SC                             0
State_WI                             0
State_KY                             0
State_LA                             0
State_OK                             0
Home.Ownership_MORTGAGE              0
Home.Ownership_RENT                  0
dtype: int64

In [75]:
ld_train=ld_all[ld_all['data']=='train']
del ld_train['data']
ld_test=ld_all[ld_all['data']=='test']
ld_test.drop(['Interest.Rate','data'],axis=1,inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_15372\2834202400.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ld_test.drop(['Interest.Rate','data'],axis=1,inplace=True)

In [76]:
del ld_all

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
ld_train1,ld_train2=train_test_split(ld_train,test_size=0.2,random_state=2)

In [79]:
# Notice that only train data is used for imputing missing values in both train and test

x_train1=ld_train1.drop('Interest.Rate',axis=1)
y_train1=ld_train1['Interest.Rate']

In [80]:
from sklearn.linear_model import LinearRegression

In [81]:
lm=LinearRegression()

In [82]:
lm.fit(x_train1,y_train1)

LinearRegression()

In [83]:
x_train1.shape

(1760, 49)

In [84]:
lm.intercept_

76.0191362205927

In [85]:
list(zip(x_train1.columns,lm.coef_))

[('Amount.Requested', 0.0001561443101214382),
 ('Debt.To.Income.Ratio', -0.0038442407741175947),
 ('Monthly.Income', -2.6406486110310904e-05),
 ('Open.CREDIT.Lines', -0.0402279979836284),
 ('Revolving.CREDIT.Balance', -4.043165672540372e-06),
 ('Inquiries.in.the.Last.6.Months', 0.33676130295646356),
 ('Employment.Length', 0.03473388302212266),
 ('fico', -0.08669304194244765),
 ('Loan.Length_36 months', -3.1425547431253777),
 ('Loan.Purpose_debt_consolidation', -0.47135975236182737),
 ('Loan.Purpose_credit_card', -0.6123429134596103),
 ('Loan.Purpose_other', 0.44626098118798185),
 ('Loan.Purpose_home_improvement', -0.3699829780973755),
 ('Loan.Purpose_major_purchase', -0.097451198372359),
 ('Loan.Purpose_small_business', 0.06251542143811362),
 ('Loan.Purpose_car', 0.018748914316903592),
 ('Loan.Purpose_wedding', -0.783052054003569),
 ('Loan.Purpose_medical', -0.42214589469286856),
 ('Loan.Purpose_moving', 1.27688882221352),
 ('State_CA', -0.291208168651918),
 ('State_NY', -0.20784181354586106),
 ('State_TX', 0.3841091731465292),
 ('State_FL', 0.004847904465573989),
 ('State_IL', -0.728594651236629),
 ('State_GA', -0.10949496877625145),
 ('State_PA', -0.6344637679429558),
 ('State_NJ', -0.5044859736086548),
 ('State_VA', -0.27041244500868505),
 ('State_MA', 0.010510217191507132),
 ('State_OH', -0.442840210132041),
 ('State_MD', -0.09859435114848565),
 ('State_NC', -0.38042248719138944),
 ('State_CO', -0.13743161843769014),
 ('State_WA', -0.32628364072969274),
 ('State_CT', 0.3654372106996538),
 ('State_AZ', 0.18311333972876911),
 ('State_MI', -0.23936223962117428),
 ('State_AL', -0.4030947504696179),
 ('State_MN', -0.15863702477325903),
 ('State_MO', -0.5142321949582142),
 ('State_NV', -0.20517727901177238),
 ('State_OR', 0.03902771379342575),
 ('State_SC', -0.05833617362312729),
 ('State_WI', -0.245120642345359),
 ('State_KY', 0.18705420527433678),
 ('State_LA', -0.13009840467168565),
 ('State_OK', -0.41921256332268214),
 ('Home.Ownership_MORTGAGE', -0.4916810221538482),
 ('Home.Ownership_RENT', -0.23217518504343052)]

In [86]:
x_train2=ld_train2.drop('Interest.Rate',axis=1)

In [87]:
predicted_ir=lm.predict(x_train2)

In [88]:
from sklearn.metrics import mean_absolute_error

In [89]:
mean_absolute_error(ld_train2['Interest.Rate'],predicted_ir)

1.6292292194609486

We know the tentative performance now, lets build the model on entire training to make prediction on test/production

In [90]:
x_train=ld_train.drop('Interest.Rate',axis=1)
y_train=ld_train['Interest.Rate']

In [91]:
lm.fit(x_train,y_train)

LinearRegression()

In [92]:
test_pred=lm.predict(ld_test)

We can write these to a csv file for submission like this:

In [93]:
pd.DataFrame(test_pred).to_csv("mysubmission.csv",index=False)

# Ridge Regression

In [94]:
from sklearn.linear_model import Ridge,Lasso
from sklearn.model_selection import GridSearchCV

In [95]:
lambdas=np.linspace(1,100,100)

In [96]:
params={'alpha':lambdas}

In [97]:
model=Ridge(fit_intercept=True)

In [98]:
grid_search=GridSearchCV(model,param_grid=params,cv=10,scoring='neg_mean_absolute_error')

In [99]:
grid_search.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=Ridge(),
             param_grid={'alpha': array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])},
             scoring='neg_mean_absolute_error')

In [100]:
grid_search.best_estimator_

Ridge(alpha=33.0)

In [101]:
grid_search.cv_results_

{'mean_fit_time': array([0.004614  , 0.00700014, 0.00400112, 0.00800157, 0.0069983 ,
        0.00500088, 0.00568833, 0.00624964, 0.00625   , 0.00312386,
        0.00162535, 0.00468719, 0.00480876, 0.00624974, 0.0078136 ,
        0.00937393, 0.00937579, 0.00625064, 0.00468755, 0.00468745,
        0.00781233, 0.00625005, 0.01093879, 0.00468709, 0.00625026,
        0.004687  , 0.00468669, 0.        , 0.00625026, 0.        ,
        0.00937374, 0.01093755, 0.00468767, 0.01093745, 0.00468862,
        0.00781186, 0.00468769, 0.00156264, 0.00624993, 0.00781281,
        0.00937495, 0.00312476, 0.00781226, 0.00625   , 0.00625052,
        0.00468714, 0.00624993, 0.0109364 , 0.01562502, 0.01093781,
        0.        , 0.01093838, 0.00156255, 0.00781169, 0.00937383,
        0.0031256 , 0.0062501 , 0.00625083, 0.00156138, 0.        ,
        0.00156267, 0.00625005, 0.00156319, 0.00937455, 0.00624945,
        0.01093743, 0.00624983, 0.00156269, 0.01093624, 0.00625055,
        0.00781302, 0.00312498, 0.00468731, 0.00468767, 0.00468791,
        0.00624976, 0.00312507, 0.00468748, 0.        , 0.00625064,
        0.00156245, 0.00468733, 0.00312469, 0.0062505 , 0.00156324,
        0.00625041, 0.00468767, 0.01093717, 0.00312443, 0.00781233,
        0.0046869 , 0.00156255, 0.00468733, 0.00937467, 0.00937507,
        0.        , 0.00781267, 0.00468779, 0.00468676, 0.00937552]),
 'std_fit_time': array([2.57939370e-03, 4.58266499e-03, 4.90034744e-03, 4.00078823e-03,
        4.58146668e-03, 5.00087788e-03, 7.13524161e-03, 7.65421852e-03,
        7.65465551e-03, 6.24771171e-03, 3.38643345e-03, 7.15980111e-03,
        5.56769254e-03, 7.65433426e-03, 7.81359803e-03, 7.65378251e-03,
        7.65529927e-03, 7.65544539e-03, 7.16034736e-03, 7.16020176e-03,
        7.81233317e-03, 7.65471470e-03, 7.16112118e-03, 7.15965556e-03,
        7.65497709e-03, 7.15950984e-03, 7.15903773e-03, 0.00000000e+00,
        7.65497697e-03, 0.00000000e+00, 7.65363050e-03, 7.16030677e-03,
        7.16052964e-03, 7.16024476e-03, 7.16198635e-03, 7.81185862e-03,
        7.16056638e-03, 4.68792915e-03, 7.65456810e-03, 7.81281240e-03,
        7.65461980e-03, 6.24952329e-03, 7.81226207e-03, 7.65465594e-03,
        7.65529814e-03, 7.15972827e-03, 7.65456788e-03, 7.15955776e-03,
        4.04672961e-06, 7.16047820e-03, 0.00000000e+00, 7.16085280e-03,
        4.68764305e-03, 7.81169018e-03, 7.65370257e-03, 6.25119248e-03,
        7.65477232e-03, 7.65567773e-03, 4.68413830e-03, 0.00000000e+00,
        4.68800068e-03, 7.65471445e-03, 4.68957424e-03, 7.65428617e-03,
        7.65398509e-03, 7.16022831e-03, 7.65445105e-03, 4.68807220e-03,
        7.15944950e-03, 7.65532759e-03, 7.81302736e-03, 6.24995232e-03,
        7.15998323e-03, 7.16053004e-03, 7.16089445e-03, 7.65436454e-03,
        6.25014305e-03, 7.16023812e-03, 0.00000000e+00, 7.65544469e-03,
        4.68735695e-03, 7.16001962e-03, 6.24938012e-03, 7.65526873e-03,
        4.68971729e-03, 7.65515216e-03, 7.16053029e-03, 7.16005626e-03,
        6.24885564e-03, 7.81233402e-03, 7.15936533e-03, 4.68764305e-03,
        7.16001960e-03, 7.65438375e-03, 7.65471398e-03, 0.00000000e+00,
        7.81266731e-03, 7.16071357e-03, 7.15914607e-03, 7.65508430e-03]),
 'mean_score_time': array([0.00349874, 0.0010006 , 0.00499768, 0.00199952, 0.00400031,
        0.00499942, 0.00205498, 0.00312605, 0.00156255, 0.00625017,
        0.01026306, 0.00781264, 0.00422261, 0.00312481, 0.00156279,
        0.        , 0.        , 0.00312467, 0.003125  , 0.00468645,
        0.        , 0.00312448, 0.00156188, 0.00312476, 0.00312529,
        0.00468814, 0.00468752, 0.00937574, 0.        , 0.00781262,
        0.        , 0.        , 0.00468731, 0.        , 0.0046865 ,
        0.00312557, 0.00156255, 0.00937505, 0.00312519, 0.00156233,
        0.        , 0.00312574, 0.        , 0.00312548, 0.00156183,
        0.00625095, 0.00156267, 0.        , 0.        , 0.00468833,
        0.0124989 , 0.        , 0.00781298, 0.0015631 , 0.00156317,
        0.00624976, 0.00312567, 0.00312417, 0.00781379, 0.00937443,
        0.0078125 , 0.00468709, 0.00937495, 0.        , 0.00468829,
        0.        , 0.00156322, 0.00937502, 0.        , 0.00312493,
        0.00156219, 0.00625021, 0.0078124 , 0.00312481, 0.00468781,
        0.00312519, 0.00625   , 0.00156238, 0.01093686, 0.00156245,
        0.00781243, 0.00156269, 0.0062505 , 0.00156281, 0.00937343,
        0.00312471, 0.00468802, 0.0015624 , 0.00625017, 0.00156243,
        0.00156245, 0.00781281, 0.003125  , 0.        , 0.        ,
        0.00781269, 0.00156271, 0.00312507, 0.00468817, 0.        ]),
 'std_score_time': array([0.00280468, 0.00300179, 0.00499768, 0.00399904, 0.00489935,
        0.00499942, 0.00411177, 0.0062521 , 0.00468764, 0.00765486,
        0.00732017, 0.00781264, 0.0058384 , 0.00624962, 0.00468836,
        0.        , 0.        , 0.00624933, 0.00625   , 0.00715867,
        0.        , 0.00624895, 0.00468564, 0.00624952, 0.00625057,
        0.00716126, 0.00716031, 0.00765526, 0.        , 0.00781262,
        0.        , 0.        , 0.00715998, 0.        , 0.00715875,
        0.00625115, 0.00468764, 0.0076547 , 0.00625038, 0.004687  ,
        0.        , 0.00625148, 0.        , 0.00625095, 0.0046855 ,
        0.00765582, 0.004688  , 0.        , 0.        , 0.00716155,
        0.00624945, 0.        , 0.00781298, 0.00468929, 0.0046895 ,
        0.00765436, 0.00625134, 0.00624833, 0.00781379, 0.00765419,
        0.0078125 , 0.00715966, 0.00765462, 0.        , 0.00716148,
        0.        , 0.00468965, 0.00765468, 0.        , 0.00624986,
        0.00468657, 0.00765492, 0.00781241, 0.00624962, 0.00716075,
        0.00625038, 0.00765466, 0.00468714, 0.00715985, 0.00468736,
        0.00781243, 0.00468807, 0.00765527, 0.00468843, 0.00765337,
        0.00624943, 0.00716108, 0.00468721, 0.00765486, 0.00468729,
        0.00468736, 0.00781281, 0.00625   , 0.        , 0.        ,
        0.00781269, 0.00468814, 0.00625014, 0.00716129, 0.        ]),
 'param_alpha': masked_array(data=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0,
                    11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0,
                    20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0,
                    29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0,
                    38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0,
                    47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0,
                    56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0,
                    65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0,
                    74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0,
                    83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0,
                    92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'alpha': 1.0},
  {'alpha': 2.0},
  {'alpha': 3.0},
  {'alpha': 4.0},
  {'alpha': 5.0},
  {'alpha': 6.0},
  {'alpha': 7.0},
  {'alpha': 8.0},
  {'alpha': 9.0},
  {'alpha': 10.0},
  {'alpha': 11.0},
  {'alpha': 12.0},
  {'alpha': 13.0},
  {'alpha': 14.0},
  {'alpha': 15.0},
  {'alpha': 16.0},
  {'alpha': 17.0},
  {'alpha': 18.0},
  {'alpha': 19.0},
  {'alpha': 20.0},
  {'alpha': 21.0},
  {'alpha': 22.0},
  {'alpha': 23.0},
  {'alpha': 24.0},
  {'alpha': 25.0},
  {'alpha': 26.0},
  {'alpha': 27.0},
  {'alpha': 28.0},
  {'alpha': 29.0},
  {'alpha': 30.0},
  {'alpha': 31.0},
  {'alpha': 32.0},
  {'alpha': 33.0},
  {'alpha': 34.0},
  {'alpha': 35.0},
  {'alpha': 36.0},
  {'alpha': 37.0},
  {'alpha': 38.0},
  {'alpha': 39.0},
  {'alpha': 40.0},
  {'alpha': 41.0},
  {'alpha': 42.0},
  {'alpha': 43.0},
  {'alpha': 44.0},
  {'alpha': 45.0},
  {'alpha': 46.0},
  {'alpha': 47.0},
  {'alpha': 48.0},
  {'alpha': 49.0},
  {'alpha': 50.0},
  {'alpha': 51.0},
  {'alpha': 52.0},
  {'alpha': 53.0},
  {'alpha': 54.0},
  {'alpha': 55.0},
  {'alpha': 56.0},
  {'alpha': 57.0},
  {'alpha': 58.0},
  {'alpha': 59.0},
  {'alpha': 60.0},
  {'alpha': 61.0},
  {'alpha': 62.0},
  {'alpha': 63.0},
  {'alpha': 64.0},
  {'alpha': 65.0},
  {'alpha': 66.0},
  {'alpha': 67.0},
  {'alpha': 68.0},
  {'alpha': 69.0},
  {'alpha': 70.0},
  {'alpha': 71.0},
  {'alpha': 72.0},
  {'alpha': 73.0},
  {'alpha': 74.0},
  {'alpha': 75.0},
  {'alpha': 76.0},
  {'alpha': 77.0},
  {'alpha': 78.0},
  {'alpha': 79.0},
  {'alpha': 80.0},
  {'alpha': 81.0},
  {'alpha': 82.0},
  {'alpha': 83.0},
  {'alpha': 84.0},
  {'alpha': 85.0},
  {'alpha': 86.0},
  {'alpha': 87.0},
  {'alpha': 88.0},
  {'alpha': 89.0},
  {'alpha': 90.0},
  {'alpha': 91.0},
  {'alpha': 92.0},
  {'alpha': 93.0},
  {'alpha': 94.0},
  {'alpha': 95.0},
  {'alpha': 96.0},
  {'alpha': 97.0},
  {'alpha': 98.0},
  {'alpha': 99.0},
  {'alpha': 100.0}],
 'split0_test_score': array([-1.72253875, -1.72334901, -1.72413461, -1.72487488, -1.72555884,
        -1.72619876, -1.72680296, -1.72739264, -1.72799979, -1.72860761,
        -1.72924003, -1.72986019, -1.73046393, -1.73105275, -1.73162788,
        -1.73219041, -1.73274126, -1.73328123, -1.73381104, -1.73433129,
        -1.73484256, -1.73534533, -1.73584005, -1.73632711, -1.7368069 ,
        -1.73727973, -1.73774592, -1.73820573, -1.73865943, -1.73910726,
        -1.73954942, -1.73998613, -1.74045126, -1.7409615 , -1.74151634,
        -1.74206533, -1.74260866, -1.74314646, -1.74367889, -1.74423658,
        -1.74490884, -1.74559775, -1.74628059, -1.74695747, -1.74762852,
        -1.74829384, -1.74895355, -1.74963028, -1.75030137, -1.75096685,
        -1.7516268 , -1.75228134, -1.75294321, -1.75361999, -1.75429091,
        -1.75495607, -1.75561557, -1.75626952, -1.75691802, -1.75756116,
        -1.75819904, -1.75883174, -1.75945935, -1.76008195, -1.76069963,
        -1.76135125, -1.76199821, -1.76264021, -1.76328149, -1.76393606,
        -1.7645857 , -1.76523048, -1.76587048, -1.76650575, -1.76713638,
        -1.76777118, -1.76841472, -1.7690536 , -1.76968788, -1.77031762,
        -1.77094289, -1.77156375, -1.77218025, -1.77279245, -1.7734004 ,
        -1.77400417, -1.77460381, -1.77519936, -1.77579088, -1.77637841,
        -1.77696202, -1.77754174, -1.77811762, -1.7786897 , -1.77925804,
        -1.77982268, -1.78038366, -1.78094102, -1.7814948 , -1.78204505]),
 'split1_test_score': array([-1.7654695 , -1.76254819, -1.75985944, -1.75760418, -1.75562082,
        -1.75378061, -1.75201293, -1.75031812, -1.74869452, -1.74719625,
        -1.74582755, -1.74451818, -1.74326483, -1.74206429, -1.74091344,
        -1.73980935, -1.73874927, -1.73777868, -1.73691135, -1.73610036,
        -1.73536048, -1.7346499 , -1.73396695, -1.73331008, -1.73267785,
        -1.73206893, -1.73148205, -1.73091605, -1.73036987, -1.72984247,
        -1.72933291, -1.72884032, -1.72836385, -1.72790275, -1.7274568 ,
        -1.72707513, -1.72670934, -1.72635564, -1.72601349, -1.72568236,
        -1.72536178, -1.72505129, -1.72475045, -1.72445886, -1.72417613,
        -1.72390189, -1.72363581, -1.72337755, -1.7231268 , -1.72288327,
        -1.72264667, -1.72241675, -1.72219325, -1.72197593, -1.72176456,
        -1.72155892, -1.72135881, -1.72116403, -1.72097439, -1.7207897 ,
        -1.72060981, -1.72043453, -1.72026372, -1.72009723, -1.71994335,
        -1.71981361, -1.71968741, -1.71956463, -1.71944516, -1.71932888,
        -1.71921568, -1.71910548, -1.71899817, -1.71889366, -1.71879186,
        -1.71869269, -1.71859605, -1.71850188, -1.71841009, -1.71832062,
        -1.71826736, -1.71821807, -1.7181708 , -1.71812546, -1.718082  ,
        -1.71804037, -1.71803622, -1.71806773, -1.71810919, -1.71815175,
        -1.71819535, -1.71823996, -1.71828553, -1.71833203, -1.71837943,
        -1.71842768, -1.71847675, -1.71852661, -1.71858255, -1.71868105]),
 'split2_test_score': array([-1.77330129, -1.77132736, -1.76955818, -1.76800466, -1.76662231,
        -1.76534921, -1.76423207, -1.76390196, -1.76360635, -1.76334008,
        -1.76309915, -1.76288041, -1.76268126, -1.76249961, -1.76233367,
        -1.76218193, -1.76204313, -1.76191612, -1.76179996, -1.76169377,
        -1.7615968 , -1.76150838, -1.76142983, -1.76139326, -1.76136284,
        -1.76133815, -1.76131881, -1.76130448, -1.76129484, -1.7612896 ,
        -1.76128849, -1.76129128, -1.76129771, -1.7613076 , -1.76132073,
        -1.76133693, -1.76135603, -1.76137786, -1.76140228, -1.76142915,
        -1.76145834, -1.7615619 , -1.76173634, -1.7619108 , -1.76208522,
        -1.76230921, -1.7625647 , -1.7628193 , -1.76307309, -1.76333176,
        -1.76358936, -1.76384588, -1.76410129, -1.76435561, -1.76460882,
        -1.76486091, -1.76511189, -1.76536174, -1.76561047, -1.76586298,
        -1.76613568, -1.7664275 , -1.7667355 , -1.7670444 , -1.76739335,
        -1.76776096, -1.76812639, -1.76848965, -1.76885077, -1.76920976,
        -1.76956663, -1.76992141, -1.77027411, -1.77064263, -1.77102285,
        -1.77140041, -1.77177533, -1.77214766, -1.77251742, -1.77288465,
        -1.77324939, -1.77361165, -1.77397149, -1.77432892, -1.77468398,
        -1.77503669, -1.77538708, -1.77573519, -1.77608103, -1.77642464,
        -1.77676604, -1.77710526, -1.77744232, -1.77777724, -1.77811006,
        -1.77844079, -1.77876946, -1.77909609, -1.7794207 , -1.77974331]),
 'split3_test_score': array([-1.64257232, -1.64188608, -1.64137536, -1.64123067, -1.64114369,
        -1.64106527, -1.64099094, -1.64091412, -1.64083459, -1.64075238,
        -1.64066765, -1.64063235, -1.64060874, -1.64058298, -1.64055526,
        -1.64052578, -1.6404947 , -1.6404759 , -1.64050422, -1.64053052,
        -1.64055491, -1.64057755, -1.64059854, -1.640618  , -1.64063602,
        -1.6406527 , -1.64066812, -1.64068236, -1.64069549, -1.64070758,
        -1.64071869, -1.64072887, -1.64073818, -1.64075221, -1.64076743,
        -1.64078198, -1.64079589, -1.64081098, -1.64083316, -1.64085481,
        -1.64087596, -1.64089662, -1.64091683, -1.6409366 , -1.64095594,
        -1.64097488, -1.64099343, -1.6410116 , -1.6410386 , -1.64108876,
        -1.64113822, -1.641187  , -1.6412351 , -1.64128256, -1.64132937,
        -1.64137557, -1.64142116, -1.64146616, -1.64151058, -1.64155444,
        -1.64159774, -1.64164051, -1.64168616, -1.64177882, -1.64188075,
        -1.64198176, -1.64208185, -1.64218106, -1.64227938, -1.64237683,
        -1.64247344, -1.64256921, -1.64266417, -1.64275831, -1.64285167,
        -1.64294424, -1.64303605, -1.6431271 , -1.6432174 , -1.64334236,
        -1.6434815 , -1.64365065, -1.64381863, -1.64398543, -1.64415105,
        -1.64431551, -1.64451128, -1.64471124, -1.64490992, -1.64512682,
        -1.6453466 , -1.64556505, -1.6457822 , -1.64599806, -1.64621263,
        -1.64642594, -1.64663799, -1.6468488 , -1.64705838, -1.64726674]),
 'split4_test_score': array([-1.45032777, -1.44944355, -1.4484879 , -1.44748883, -1.44647726,
        -1.4454701 , -1.44447677, -1.44350249, -1.44256588, -1.44168861,
        -1.44085813, -1.44006867, -1.43930796, -1.43863644, -1.43798283,
        -1.43734646, -1.43672661, -1.43612257, -1.43553361, -1.43495906,
        -1.43439823, -1.43385049, -1.43331895, -1.43280049, -1.43229345,
        -1.43187231, -1.43147328, -1.43109384, -1.43077346, -1.43046125,
        -1.4301564 , -1.42985855, -1.42959562, -1.42936848, -1.42914728,
        -1.42893174, -1.42872162, -1.42851666, -1.42831665, -1.42812138,
        -1.4279489 , -1.42778697, -1.42762858, -1.42749047, -1.42738814,
        -1.42732973, -1.42727366, -1.42721981, -1.42716809, -1.42711841,
        -1.42707066, -1.42702478, -1.42698067, -1.42697524, -1.42697527,
        -1.42697639, -1.42697854, -1.42698166, -1.42698571, -1.42699065,
        -1.42699643, -1.42700301, -1.42701035, -1.42701842, -1.42702718,
        -1.427038  , -1.427077  , -1.4271164 , -1.42715618, -1.42719631,
        -1.42723676, -1.42727752, -1.42731857, -1.42737806, -1.42748368,
        -1.42759128, -1.42769828, -1.42780465, -1.42791043, -1.42801559,
        -1.42812016, -1.42822413, -1.42832751, -1.4284303 , -1.4285325 ,
        -1.42863413, -1.42873517, -1.42883565, -1.42893556, -1.42905029,
        -1.42918566, -1.42932026, -1.42945411, -1.42958721, -1.42972478,
        -1.42988176, -1.43003782, -1.43019296, -1.43034719, -1.43050051]),
 'split5_test_score': array([-1.64004633, -1.63901912, -1.63809581, -1.63724413, -1.63644519,
        -1.63571198, -1.63503705, -1.63438817, -1.63376158, -1.63315448,
        -1.63256471, -1.63199058, -1.63143075, -1.63088408, -1.63034965,
        -1.62982668, -1.62931551, -1.62881538, -1.62832496, -1.62784377,
        -1.6273714 , -1.62690747, -1.62645163, -1.62600355, -1.62556295,
        -1.62512954, -1.62470308, -1.62428332, -1.62389331, -1.62352364,
        -1.6231607 , -1.62280427, -1.62245412, -1.62211005, -1.62177185,
        -1.62143935, -1.62111236, -1.62079073, -1.62047427, -1.62016285,
        -1.61985632, -1.61955454, -1.61925736, -1.61896467, -1.61870472,
        -1.61850196, -1.61830247, -1.61811862, -1.61795548, -1.61779498,
        -1.61763706, -1.61748165, -1.61732867, -1.61717806, -1.61702977,
        -1.61691654, -1.61682553, -1.61673638, -1.61664903, -1.61656344,
        -1.61647955, -1.61639732, -1.61631671, -1.61623766, -1.61616015,
        -1.61608412, -1.61600953, -1.61593636, -1.61590137, -1.61587843,
        -1.61585653, -1.61583566, -1.61581576, -1.61579683, -1.61577882,
        -1.61576171, -1.61574548, -1.61573824, -1.61573343, -1.61572926,
        -1.61572573, -1.61572281, -1.61575581, -1.61580089, -1.6158461 ,
        -1.61589143, -1.61593686, -1.61598239, -1.616028  , -1.6160737 ,
        -1.61612519, -1.6161877 , -1.61625009, -1.6163323 , -1.61643082,
        -1.61652898, -1.61662679, -1.61672424, -1.61682134, -1.61691809]),
 'split6_test_score': array([-1.42603072, -1.42527953, -1.42460292, -1.42412197, -1.42377146,
        -1.42343705, -1.4231159 , -1.4228061 , -1.42250629, -1.42223274,
        -1.42201914, -1.42187527, -1.42174739, -1.4216242 , -1.42150551,
        -1.42139111, -1.42128084, -1.42118202, -1.42110588, -1.42103293,
        -1.42097021, -1.42094471, -1.42094401, -1.42095835, -1.42097542,
        -1.4209951 , -1.4210173 , -1.42104192, -1.42106888, -1.42109809,
        -1.42112945, -1.4211629 , -1.42119835, -1.42123572, -1.42127494,
        -1.42131595, -1.4213738 , -1.42146381, -1.42155485, -1.42164688,
        -1.42173985, -1.42183372, -1.42192844, -1.42202587, -1.42213753,
        -1.42224978, -1.42236257, -1.42247587, -1.42258965, -1.42270387,
        -1.42281851, -1.42293354, -1.42304892, -1.42316463, -1.42328064,
        -1.42340141, -1.42353523, -1.42366914, -1.42380312, -1.42393716,
        -1.42407124, -1.42420534, -1.42433945, -1.42451598, -1.42475455,
        -1.42499237, -1.42522943, -1.42546573, -1.42570126, -1.4259389 ,
        -1.42620193, -1.42646403, -1.42672515, -1.42698528, -1.42724444,
        -1.42750261, -1.42775981, -1.42801602, -1.42827125, -1.4285255 ,
        -1.42877877, -1.42903107, -1.42928633, -1.42956319, -1.42983893,
        -1.43016156, -1.43049875, -1.43083428, -1.43116817, -1.43150043,

if you want you can now fit a ridge regression model with obtained value of alpha , although there is no need, grid search 
automatically fits the best estimator on the entire data, you can directly use this to make predictions on test_data. But if 
you want to look at coefficients , its much more convenient to fit the model with direct function

Using the report function given below you can see the cs performance of top few models as well, that will the 
tentative performance

In [102]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                    results['mean_test_score'][candidate],
                    results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [103]:
report(grid_search.cv_results_,100)

Model with rank: 1
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 33.0}

Model with rank: 2
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 34.0}

Model with rank: 3
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 32.0}

Model with rank: 4
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 35.0}

Model with rank: 5
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 31.0}

Model with rank: 6
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 36.0}

Model with rank: 7
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 30.0}

Model with rank: 8
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 37.0}

Model with rank: 9
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 29.0}

Model with rank: 10
Mean validation score: -1.610 (std: 0.118)
Parameters: {'alpha': 38.0}

Model with rank: 11
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 28.0}

Model with rank: 12
Mean validation score: -1.610 (std: 0.118)
Parameters: {'alpha': 39.0}

Model with rank: 13
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 27.0}

Model with rank: 14
Mean validation score: -1.610 (std: 0.118)
Parameters: {'alpha': 40.0}

Model with rank: 15
Mean validation score: -1.610 (std: 0.117)
Parameters: {'alpha': 26.0}

Model with rank: 16
Mean validation score: -1.610 (std: 0.118)
Parameters: {'alpha': 41.0}

Model with rank: 17
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 25.0}

Model with rank: 18
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 42.0}

Model with rank: 19
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 24.0}

Model with rank: 20
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 43.0}

Model with rank: 21
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 23.0}

Model with rank: 22
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 44.0}

Model with rank: 23
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 22.0}

Model with rank: 24
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 45.0}

Model with rank: 25
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 21.0}

Model with rank: 26
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 46.0}

Model with rank: 27
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 20.0}

Model with rank: 28
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 47.0}

Model with rank: 29
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 19.0}

Model with rank: 30
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 48.0}

Model with rank: 31
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 18.0}

Model with rank: 32
Mean validation score: -1.611 (std: 0.119)
Parameters: {'alpha': 49.0}

Model with rank: 33
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 17.0}

Model with rank: 34
Mean validation score: -1.611 (std: 0.119)
Parameters: {'alpha': 50.0}

Model with rank: 35
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 16.0}

Model with rank: 36
Mean validation score: -1.612 (std: 0.119)
Parameters: {'alpha': 51.0}

Model with rank: 37
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 15.0}

Model with rank: 38
Mean validation score: -1.612 (std: 0.119)
Parameters: {'alpha': 52.0}

Model with rank: 39
Mean validation score: -1.612 (std: 0.119)
Parameters: {'alpha': 53.0}

Model with rank: 40
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 14.0}

Model with rank: 41
Mean validation score: -1.612 (std: 0.119)
Parameters: {'alpha': 54.0}

Model with rank: 42
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 13.0}

Model with rank: 43
Mean validation score: -1.612 (std: 0.119)
Parameters: {'alpha': 55.0}

Model with rank: 44
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 12.0}

Model with rank: 45
Mean validation score: -1.612 (std: 0.119)
Parameters: {'alpha': 56.0}

Model with rank: 46
Mean validation score: -1.613 (std: 0.119)
Parameters: {'alpha': 57.0}

Model with rank: 47
Mean validation score: -1.613 (std: 0.116)
Parameters: {'alpha': 11.0}

Model with rank: 48
Mean validation score: -1.613 (std: 0.119)
Parameters: {'alpha': 58.0}

Model with rank: 49
Mean validation score: -1.613 (std: 0.120)
Parameters: {'alpha': 59.0}

Model with rank: 50
Mean validation score: -1.613 (std: 0.115)
Parameters: {'alpha': 10.0}

Model with rank: 51
Mean validation score: -1.613 (std: 0.120)
Parameters: {'alpha': 60.0}

Model with rank: 52
Mean validation score: -1.613 (std: 0.120)
Parameters: {'alpha': 61.0}

Model with rank: 53
Mean validation score: -1.613 (std: 0.115)
Parameters: {'alpha': 9.0}

Model with rank: 54
Mean validation score: -1.614 (std: 0.120)
Parameters: {'alpha': 62.0}

Model with rank: 55
Mean validation score: -1.614 (std: 0.120)
Parameters: {'alpha': 63.0}

Model with rank: 56
Mean validation score: -1.614 (std: 0.115)
Parameters: {'alpha': 8.0}

Model with rank: 57
Mean validation score: -1.614 (std: 0.120)
Parameters: {'alpha': 64.0}

Model with rank: 58
Mean validation score: -1.614 (std: 0.120)
Parameters: {'alpha': 65.0}

Model with rank: 59
Mean validation score: -1.614 (std: 0.115)
Parameters: {'alpha': 7.0}

Model with rank: 60
Mean validation score: -1.614 (std: 0.120)
Parameters: {'alpha': 66.0}

Model with rank: 61
Mean validation score: -1.615 (std: 0.120)
Parameters: {'alpha': 67.0}

Model with rank: 62
Mean validation score: -1.615 (std: 0.115)
Parameters: {'alpha': 6.0}

Model with rank: 63
Mean validation score: -1.615 (std: 0.120)
Parameters: {'alpha': 68.0}

Model with rank: 64
Mean validation score: -1.615 (std: 0.120)
Parameters: {'alpha': 69.0}

Model with rank: 65
Mean validation score: -1.615 (std: 0.120)
Parameters: {'alpha': 70.0}

Model with rank: 66
Mean validation score: -1.615 (std: 0.115)
Parameters: {'alpha': 5.0}

Model with rank: 67
Mean validation score: -1.616 (std: 0.121)
Parameters: {'alpha': 71.0}

Model with rank: 68
Mean validation score: -1.616 (std: 0.121)
Parameters: {'alpha': 72.0}

Model with rank: 69
Mean validation score: -1.616 (std: 0.115)
Parameters: {'alpha': 4.0}

Model with rank: 70
Mean validation score: -1.616 (std: 0.121)
Parameters: {'alpha': 73.0}

Model with rank: 71
Mean validation score: -1.616 (std: 0.121)
Parameters: {'alpha': 74.0}

Model with rank: 72
Mean validation score: -1.617 (std: 0.121)
Parameters: {'alpha': 75.0}

Model with rank: 73
Mean validation score: -1.617 (std: 0.116)
Parameters: {'alpha': 3.0}

Model with rank: 74
Mean validation score: -1.617 (std: 0.121)
Parameters: {'alpha': 76.0}

Model with rank: 75
Mean validation score: -1.617 (std: 0.121)
Parameters: {'alpha': 77.0}

Model with rank: 76
Mean validation score: -1.617 (std: 0.121)
Parameters: {'alpha': 78.0}

Model with rank: 77
Mean validation score: -1.618 (std: 0.121)
Parameters: {'alpha': 79.0}

Model with rank: 78
Mean validation score: -1.618 (std: 0.116)
Parameters: {'alpha': 2.0}

Model with rank: 79
Mean validation score: -1.618 (std: 0.121)
Parameters: {'alpha': 80.0}

Model with rank: 80
Mean validation score: -1.618 (std: 0.121)
Parameters: {'alpha': 81.0}

Model with rank: 81
Mean validation score: -1.618 (std: 0.121)
Parameters: {'alpha': 82.0}

Model with rank: 82
Mean validation score: -1.619 (std: 0.116)
Parameters: {'alpha': 1.0}

Model with rank: 83
Mean validation score: -1.619 (std: 0.122)
Parameters: {'alpha': 83.0}

Model with rank: 84
Mean validation score: -1.619 (std: 0.122)
Parameters: {'alpha': 84.0}

Model with rank: 85
Mean validation score: -1.619 (std: 0.122)
Parameters: {'alpha': 85.0}

Model with rank: 86
Mean validation score: -1.620 (std: 0.122)
Parameters: {'alpha': 86.0}

Model with rank: 87
Mean validation score: -1.620 (std: 0.122)
Parameters: {'alpha': 87.0}

Model with rank: 88
Mean validation score: -1.620 (std: 0.122)
Parameters: {'alpha': 88.0}

Model with rank: 89
Mean validation score: -1.620 (std: 0.122)
Parameters: {'alpha': 89.0}

Model with rank: 90
Mean validation score: -1.621 (std: 0.122)
Parameters: {'alpha': 90.0}

Model with rank: 91
Mean validation score: -1.621 (std: 0.122)
Parameters: {'alpha': 91.0}

Model with rank: 92
Mean validation score: -1.621 (std: 0.122)
Parameters: {'alpha': 92.0}

Model with rank: 93
Mean validation score: -1.622 (std: 0.122)
Parameters: {'alpha': 93.0}

Model with rank: 94
Mean validation score: -1.622 (std: 0.122)
Parameters: {'alpha': 94.0}

Model with rank: 95
Mean validation score: -1.622 (std: 0.122)
Parameters: {'alpha': 95.0}

Model with rank: 96
Mean validation score: -1.622 (std: 0.122)
Parameters: {'alpha': 96.0}

Model with rank: 97
Mean validation score: -1.623 (std: 0.122)
Parameters: {'alpha': 97.0}

Model with rank: 98
Mean validation score: -1.623 (std: 0.122)
Parameters: {'alpha': 98.0}

Model with rank: 99
Mean validation score: -1.623 (std: 0.123)
Parameters: {'alpha': 99.0}

Model with rank: 100
Mean validation score: -1.624 (std: 0.123)
Parameters: {'alpha': 100.0}

In [104]:
test_pred=grid_search.predict(ld_test)

In [105]:
pd.DataFrame(test_pred).to_csv("mysubmission.csv",index=False)

# For looking at coefficients

In [106]:
ridge_model=grid_search.best_estimator_

In [107]:
ridge_model.fit(x_train,y_train)

Ridge(alpha=33.0)

In [108]:
list(zip(x_train1.columns,ridge_model.coef_))

[('Amount.Requested', 0.00016694728491458563),
 ('Debt.To.Income.Ratio', -0.0012318165592272812),
 ('Monthly.Income', -2.958745941066143e-05),
 ('Open.CREDIT.Lines', -0.036844456548317195),
 ('Revolving.CREDIT.Balance', -3.0298763520014647e-06),
 ('Inquiries.in.the.Last.6.Months', 0.34256440527076776),
 ('Employment.Length', 0.019386236424857758),
 ('fico', -0.0866470894033935),
 ('Loan.Length_36 months', -2.8391539157194545),
 ('Loan.Purpose_debt_consolidation', -0.37224429580381174),
 ('Loan.Purpose_credit_card', -0.4669643121927723),
 ('Loan.Purpose_other', 0.37826730338506587),
 ('Loan.Purpose_home_improvement', -0.23409022842016053),
 ('Loan.Purpose_major_purchase', -0.013616976256589884),
 ('Loan.Purpose_small_business', 0.08759197675127452),
 ('Loan.Purpose_car', -0.03257553103244007),
 ('Loan.Purpose_wedding', -0.3347599518867084),
 ('Loan.Purpose_medical', -0.09809622633427419),
 ('Loan.Purpose_moving', 0.46418890336399576),
 ('State_CA', -0.09953195660418734),
 ('State_NY', -0.05010586258365044),
 ('State_TX', 0.4246877237607747),
 ('State_FL', 0.019156225627726883),
 ('State_IL', -0.35516156308015384),
 ('State_GA', -0.08937978986862502),
 ('State_PA', -0.2884488285398782),
 ('State_NJ', -0.2158260035578721),
 ('State_VA', -0.0068205341186680256),
 ('State_MA', -0.021151484211526666),
 ('State_OH', -0.13837526923960863),
 ('State_MD', 0.0074043188758405225),
 ('State_NC', -0.250552990250435),
 ('State_CO', 0.08955252000003118),
 ('State_WA', -0.0932608015225566),
 ('State_CT', 0.2487011005044037),
 ('State_AZ', 0.2753625745253661),
 ('State_MI', -0.007178475477557746),
 ('State_AL', 0.009932143762134246),
 ('State_MN', -0.047041779455303925),
 ('State_MO', -0.12622562059305956),
 ('State_NV', -0.01649166255728207),
 ('State_OR', 0.042979132776075735),
 ('State_SC', 0.00610011793845434),
 ('State_WI', 0.06329473893294685),
 ('State_KY', 0.06769778677841294),
 ('State_LA', 0.10832206261195172),
 ('State_OK', -0.09254255640581448),
 ('Home.Ownership_MORTGAGE', -0.305146341684624),
 ('Home.Ownership_RENT', -0.09822137961739777)]

# Lasso Regression

In [113]:
lambdas = np.linspace(1,10,100)
model=Lasso(fit_intercept=True)
params={'alpha':lambdas}

In [116]:
grid_search=GridSearchCV(model,param_grid=params,cv=10,scoring='neg_mean_absolute_error')

In [117]:
grid_search.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=Lasso(),
             param_grid={'alpha': array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3....
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27272727,
        7.36363636,  7.45454545,  7.54545455,  7.63636364,  7.72727273,
        7.81818182,  7.90909091,  8.        ,  8.09090909,  8.18181818,
        8.27272727,  8.36363636,  8.45454545,  8.54545455,  8.63636364,
        8.72727273,  8.81818182,  8.90909091,  9.        ,  9.09090909,
        9.18181818,  9.27272727,  9.36363636,  9.45454545,  9.54545455,
        9.63636364,  9.72727273,  9.81818182,  9.90909091, 10.        ])},
             scoring='neg_mean_absolute_error')

In [118]:
grid_search.best_estimator_

Lasso()

you can see that, the best value of alpha comes at the edge of the range that we tried , we should expand the trial range on 
that side and run this again

In [119]:
lambdas=np.linspace(.001,2,100)
params={'alpha':lambdas}

In [120]:
grid_search=GridSearchCV(model,param_grid=params,cv=10,scoring='neg_mean_absolute_error')
grid_search.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=Lasso(),
             param_grid={'alpha': array([1.00000000e-03, 2.11919192e-02, 4.13838384e-02, 6.15757576e-02,
       8.17676768e-02, 1.01959596e-01, 1.22151515e-01, 1.42343434e-01,
       1.62535354e-01, 1.82727273e-01, 2.02919192e-01, 2.23111111e-01,
       2.43303030e-01, 2.63494949e-01, 2.83686869e-01, 3.03878788e-01,
       3.24070707e-01, 3.44262626e-01, 3.64454545e-01, 3...
       1.53558586e+00, 1.55577778e+00, 1.57596970e+00, 1.59616162e+00,
       1.61635354e+00, 1.63654545e+00, 1.65673737e+00, 1.67692929e+00,
       1.69712121e+00, 1.71731313e+00, 1.73750505e+00, 1.75769697e+00,
       1.77788889e+00, 1.79808081e+00, 1.81827273e+00, 1.83846465e+00,
       1.85865657e+00, 1.87884848e+00, 1.89904040e+00, 1.91923232e+00,
       1.93942424e+00, 1.95961616e+00, 1.97980808e+00, 2.00000000e+00])},
             scoring='neg_mean_absolute_error')

In [121]:
grid_search.best_estimator_

Lasso(alpha=0.021191919191919192)

In [122]:
report(grid_search.cv_results_,5)

Model with rank: 1
Mean validation score: -1.603 (std: 0.120)
Parameters: {'alpha': 0.021191919191919192}

Model with rank: 2
Mean validation score: -1.612 (std: 0.126)
Parameters: {'alpha': 0.041383838383838384}

Model with rank: 3
Mean validation score: -1.615 (std: 0.116)
Parameters: {'alpha': 0.001}

Model with rank: 4
Mean validation score: -1.619 (std: 0.127)
Parameters: {'alpha': 0.061575757575757575}

Model with rank: 5
Mean validation score: -1.624 (std: 0.128)
Parameters: {'alpha': 0.08176767676767677}

In [123]:
lasso_model=grid_search.best_estimator_

In [124]:
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.021191919191919192)

In [125]:
list(zip(x_train.columns,lasso_model.coef_))

[('Amount.Requested', 0.00016025576388069374),
 ('Debt.To.Income.Ratio', -0.0009940455335086431),
 ('Monthly.Income', -2.7161150694601474e-05),
 ('Open.CREDIT.Lines', -0.03776066942268258),
 ('Revolving.CREDIT.Balance', -3.2291582902347866e-06),
 ('Inquiries.in.the.Last.6.Months', 0.32734647665538585),
 ('Employment.Length', 0.011883001638602755),
 ('fico', -0.08647817945138424),
 ('Loan.Length_36 months', -3.0098932744846625),
 ('Loan.Purpose_debt_consolidation', -0.1780182230425123),
 ('Loan.Purpose_credit_card', -0.22053269213383622),
 ('Loan.Purpose_other', 0.3196217853383159),
 ('Loan.Purpose_home_improvement', -0.0),
 ('Loan.Purpose_major_purchase', 0.0),
 ('Loan.Purpose_small_business', 0.0),
 ('Loan.Purpose_car', 0.0),
 ('Loan.Purpose_wedding', -0.0),
 ('Loan.Purpose_medical', -0.0),
 ('Loan.Purpose_moving', 0.0),
 ('State_CA', -0.0),
 ('State_NY', 0.0),
 ('State_TX', 0.2592516325019152),
 ('State_FL', 0.0),
 ('State_IL', -0.0),
 ('State_GA', -0.0),
 ('State_PA', -0.0),
 ('State_NJ', -0.0),
 ('State_VA', 0.0),
 ('State_MA', 0.0),
 ('State_OH', -0.0),
 ('State_MD', 0.0),
 ('State_NC', -0.0),
 ('State_CO', 0.0),
 ('State_WA', -0.0),
 ('State_CT', 0.0),
 ('State_AZ', 0.0),
 ('State_MI', 0.0),
 ('State_AL', 0.0),
 ('State_MN', -0.0),
 ('State_MO', -0.0),
 ('State_NV', 0.0),
 ('State_OR', 0.0),
 ('State_SC', 0.0),
 ('State_WI', 0.0),
 ('State_KY', 0.0),
 ('State_LA', 0.0),
 ('State_OK', -0.0),
 ('Home.Ownership_MORTGAGE', -0.15598777750113385),
 ('Home.Ownership_RENT', 0.0)]